export type WorldCupTeam = {
  name: string;
  logo: string;
  confederation: string;
};

export const worldCupTeams: WorldCupTeam[] = [
  { name: "Канада", logo: "🇨🇦", confederation: "Хозяева" },
  { name: "Мексика", logo: "🇲🇽", confederation: "Хозяева" },
  { name: "США", logo: "🇺🇸", confederation: "Хозяева" },
  { name: "Австралия", logo: "🇦🇺", confederation: "AFC" },
  { name: "Ирак", logo: "🇮🇶", confederation: "AFC" },
  { name: "Иран", logo: "🇮🇷", confederation: "AFC" },
  { name: "Япония", logo: "🇯🇵", confederation: "AFC" },
  { name: "Иордания", logo: "🇯🇴", confederation: "AFC" },
  { name: "Южная Корея", logo: "🇰🇷", confederation: "AFC" },
  { name: "Катар", logo: "🇶🇦", confederation: "AFC" },
  { name: "Саудовская Аравия", logo: "🇸🇦", confederation: "AFC" },
  { name: "Узбекистан", logo: "🇺🇿", confederation: "AFC" },
  { name: "Алжир", logo: "🇩🇿", confederation: "CAF" },
  { name: "Кабо-Верде", logo: "🇨🇻", confederation: "CAF" },
  { name: "ДР Конго", logo: "🇨🇩", confederation: "CAF" },
  { name: "Кот-д'Ивуар", logo: "🇨🇮", confederation: "CAF" },
  { name: "Египет", logo: "🇪🇬", confederation: "CAF" },
  { name: "Гана", logo: "🇬🇭", confederation: "CAF" },
  { name: "Марокко", logo: "🇲🇦", confederation: "CAF" },
  { name: "Сенегал", logo: "🇸🇳", confederation: "CAF" },
  { name: "ЮАР", logo: "🇿🇦", confederation: "CAF" },
  { name: "Тунис", logo: "🇹🇳", confederation: "CAF" },
  { name: "Кюрасао", logo: "🇨🇼", confederation: "Concacaf" },
  { name: "Гаити", logo: "🇭🇹", confederation: "Concacaf" },
  { name: "Панама", logo: "🇵🇦", confederation: "Concacaf" },
  { name: "Аргентина", logo: "🇦🇷", confederation: "CONMEBOL" },
  { name: "Бразилия", logo: "🇧🇷", confederation: "CONMEBOL" },
  { name: "Колумбия", logo: "🇨🇴", confederation: "CONMEBOL" },
  { name: "Эквадор", logo: "🇪🇨", confederation: "CONMEBOL" },
  { name: "Парагвай", logo: "🇵🇾", confederation: "CONMEBOL" },
  { name: "Уругвай", logo: "🇺🇾", confederation: "CONMEBOL" },
  { name: "Новая Зеландия", logo: "🇳🇿", confederation: "OFC" },
  { name: "Австрия", logo: "🇦🇹", confederation: "UEFA" },
  { name: "Бельгия", logo: "🇧🇪", confederation: "UEFA" },
  { name: "Босния и Герцеговина", logo: "🇧🇦", confederation: "UEFA" },
  { name: "Хорватия", logo: "🇭🇷", confederation: "UEFA" },
  { name: "Чехия", logo: "🇨🇿", confederation: "UEFA" },
  { name: "Англия", logo: "🏴", confederation: "UEFA" },
  { name: "Франция", logo: "🇫🇷", confederation: "UEFA" },
  { name: "Германия", logo: "🇩🇪", confederation: "UEFA" },
  { name: "Нидерланды", logo: "🇳🇱", confederation: "UEFA" },
  { name: "Норвегия", logo: "🇳🇴", confederation: "UEFA" },
  { name: "Португалия", logo: "🇵🇹", confederation: "UEFA" },
  { name: "Шотландия", logo: "🏴", confederation: "UEFA" },
  { name: "Испания", logo: "🇪🇸", confederation: "UEFA" },
  { name: "Швеция", logo: "🇸🇪", confederation: "UEFA" },
  { name: "Швейцария", logo: "🇨🇭", confederation: "UEFA" },
  { name: "Турция", logo: "🇹🇷", confederation: "UEFA" },
];
